/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import { AxiosRequestConfig } from "axios";
import {
  QuotesApi,
  AuthorizationApi,
  LeadsApi,
  LocationsApi,
  OrdersApi,
  PostalCodesApi,
  QuoteInventoryApi,
  QuoteServiceGroupsApi,
} from "./api";
import { Configuration, ConfigurationParameters } from "./configuration";
import { BellhopCustom } from "./client-custom";

export class Bellhop extends BellhopCustom {
  readonly quotes: QuotesApi;
  readonly authorization: AuthorizationApi;
  readonly leads: LeadsApi;
  readonly locations: LocationsApi;
  readonly orders: OrdersApi;
  readonly postalCodes: PostalCodesApi;
  readonly quoteInventory: QuoteInventoryApi;
  readonly quoteServiceGroups: QuoteServiceGroupsApi;

  constructor(configurationParameters: ConfigurationParameters = {}) {
    super(configurationParameters);
    const configuration = new Configuration(configurationParameters);
    this.quotes = new QuotesApi(configuration);
    this.authorization = new AuthorizationApi(configuration);
    this.leads = new LeadsApi(configuration);
    this.locations = new LocationsApi(configuration);
    this.orders = new OrdersApi(configuration);
    this.postalCodes = new PostalCodesApi(configuration);
    this.quoteInventory = new QuoteInventoryApi(configuration);
    this.quoteServiceGroups = new QuoteServiceGroupsApi(configuration);
  }

}
