{
  "openapi": "3.0.3",
  "info": {
    "title": "partner-api",
    "description": "Bellhop's Partner API",
    "version": "5",
    "contact": {
      "name": "Bellhop Engineering",
      "url": "http://www.bellhop.com/",
      "email": "engineering@bellhop.com"
    },
    "x-konfig-ignore": {
      "potential-incorrect-type": true
    }
  },
  "servers": [
    {
      "description": "Development",
      "url": "https://partners.bellhops.dev/v5"
    },
    {
      "description": "Production",
      "url": "https://partners.bellhop.com/v5"
    }
  ],
  "tags": [
    {
      "name": "QuoteServiceGroup"
    },
    {
      "name": "Lead"
    },
    {
      "name": "Quote"
    },
    {
      "name": "PostalCode"
    },
    {
      "name": "Location"
    },
    {
      "name": "Order"
    }
  ],
  "paths": {
    "/postal-codes/serviceability": {
      "get": {
        "tags": [
          "PostalCode"
        ],
        "summary": "Get Postal Codes Serviceability V5",
        "operationId": "PostalCode_serviceability",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ]
      }
    },
    "/leads": {
      "post": {
        "tags": [
          "Lead"
        ],
        "summary": "Create Lead",
        "operationId": "Lead_create",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Lead"
        ],
        "summary": "List Leads",
        "operationId": "Lead_list",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ]
      }
    },
    "/leads/{lead_id}": {
      "get": {
        "tags": [
          "Lead"
        ],
        "summary": "Get Lead",
        "operationId": "Lead_get",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Lead"
        ],
        "summary": "Cancel Lead",
        "operationId": "Lead_delete",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ]
      },
      "patch": {
        "tags": [
          "Lead"
        ],
        "summary": "Update Lead",
        "operationId": "Lead_update",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ],
        "description": "Update attributes of a lead.\n\n:lead_id: The ID of the lead to update. This can be either the bellhop id or the external_id."
      }
    },
    "/quotes/{quote_id}": {
      "get": {
        "tags": [
          "Quote"
        ],
        "summary": "Get Quote",
        "operationId": "Quote_get",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ],
        "description": "Fetch a quote by ID"
      }
    },
    "/quotes": {
      "post": {
        "tags": [
          "Quote"
        ],
        "summary": "Create Quote",
        "operationId": "Quote_create",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "create:quotes"
            ]
          }
        ],
        "description": "Creates a quote\n\nCreates a quote for a given customer using the provided locations and service code.\nThe LOCALFULLSERVICE service code will generate a service group with\nLOADINGUNLOADING and TRANSIT services.\nAll other service codes generate service groups with a single service."
      }
    },
    "/quotes/{quote_id}/service-groups": {
      "post": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Create Service Group",
        "operationId": "QuoteServiceGroup_create",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "create:quotes"
            ]
          }
        ],
        "description": "Creates a new service group\n\nA service group is a collection of services that are performed at the\nsame time and location.\nThe created service group will be created with the provided services,\nlocations, and start date time.\nThe workers, duration, and end date time will be estimated based on the\nlocations and inventory attached to the quote."
      }
    },
    "/quotes/service_groups/{service_group_id}/locations": {
      "put": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Change Locations On Service Group",
        "operationId": "QuoteServiceGroups_changeLocations",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "create:quotes"
            ]
          }
        ],
        "description": "Overwrite the locations on a service group\n\nThe locations included in the request are overwritten as the locations on\nthe service group maintaining the sequence in the request.\nThis action triggers a re-estimation of the service group using the new locations."
      }
    },
    "/quotes/{quote_id}/service-group/{service_group_id}": {
      "get": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Get Service Group",
        "operationId": "QuoteServiceGroups_get",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "read:quotes"
            ]
          }
        ],
        "description": "Fetch a service group by quote ID and service group ID"
      },
      "delete": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Delete Service Group",
        "operationId": "QuoteServiceGroups_delete",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "delete:quotes"
            ]
          }
        ],
        "description": "Delete a service group by quote ID and service group ID"
      }
    },
    "/quotes/{quote_id}/service-groups/{service_group_id}": {
      "patch": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Replace Service Group",
        "operationId": "QuoteServiceGroup_update",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "update:quotes"
            ]
          }
        ],
        "description": "Replaces a service group with a flexible service group\n\nReplaces the existing service group with the selected flexible service group."
      }
    },
    "/quotes/{quote_id}/service-groups/{service_group_id}/services": {
      "put": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Update Service Group Services",
        "operationId": "QuoteServiceGroup_updateServices",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "update:quotes"
            ]
          }
        ],
        "description": "Update the service configuration on a service group\n\nUpdate services, workers and duration on a service group.\nthe service_workers object is a mapping of service code and number of workers.\n\nOnly the included service codes will be retained on the service group.\n\nAny excluded services will be removed."
      }
    },
    "/quotes/{quote_id}/service-groups/{service_group_id}/flexible": {
      "post": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Create Flexible Service Groups",
        "operationId": "QuoteServiceGroup_createFlexible",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "update:quotes"
            ]
          }
        ],
        "description": "Creates an array of flexible service groups from a service group\n\nGenerate an array of flexible service groups. The services and locations\nwill be copied from the source service group.\nOne flexible service group will be created for each day and hour combination in the input."
      }
    },
    "/quotes/{quote_id}/inventory": {
      "put": {
        "tags": [
          "Quote"
        ],
        "summary": "Update Quote Inventory",
        "operationId": "Quote_updateInventory",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "update:quotes"
            ]
          }
        ]
      },
      "delete": {
        "tags": [
          "Quote"
        ],
        "summary": "Delete Quote Inventory",
        "operationId": "Quote_deleteInventory",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "delete:quotes"
            ]
          }
        ]
      },
      "get": {
        "tags": [
          "Quote"
        ],
        "summary": "Get Quote Inventory",
        "operationId": "Quote_getInventory",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "read:quotes"
            ]
          }
        ]
      }
    },
    "/quotes/service-groups/{service_group_id}/estimate": {
      "post": {
        "tags": [
          "QuoteServiceGroup"
        ],
        "summary": "Get Service Group Estimate",
        "operationId": "QuoteServiceGroup_createEstimate",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "read:quotes"
            ]
          }
        ]
      }
    },
    "/locations": {
      "post": {
        "tags": [
          "Location"
        ],
        "summary": "Create Quoting Location",
        "operationId": "Location_create",
        "security": [
          {
            "OAuth2ImplicitBearer": [
              "create:locations"
            ]
          }
        ],
        "description": "Create quoting location object from address\n\nCreate Quoting Location standardizes input address via USPS and generates\ngeo-location details Google Maps APIs.\nThe location id is a hash of the required fields on the location object."
      }
    },
    "/orders/{quote_id}": {
      "post": {
        "tags": [
          "Order"
        ],
        "summary": "Create Order",
        "operationId": "Order_create",
        "security": [
          {
            "OAuth2ImplicitBearer": [
            ]
          }
        ],
        "description": "Creates an order from a quote"
      }
    }
  },
  "components": {
    "securitySchemes": {
      "OAuth2ImplicitBearer": {
        "type": "oauth2",
        "flows": {
          "implicit": {
            "scopes": {
            },
            "authorizationUrl": "/authorize"
          }
        }
      }
    }
  }
}