# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest

import bellhop
from bellhop.model.find_by_tags_response import FindByTagsResponse
from bellhop import configuration


class TestFindByTagsResponse(unittest.TestCase):
    """FindByTagsResponse unit test stubs"""
    pass


if __name__ == '__main__':
    unittest.main()
