/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5.0.0
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { AccountSourceNullable } from './account-source-nullable';
import { CreateCustomerAccountRequest } from './create-customer-account-request';
import { CustomerStatusNullable } from './customer-status-nullable';
import { HearAboutUsNullable } from './hear-about-us-nullable';

/**
 * Customer information
 * @export
 * @interface CreateQuoteRequestCustomer
 */
export interface CreateQuoteRequestCustomer {
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequestCustomer
     */
    'first_name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequestCustomer
     */
    'last_name': string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequestCustomer
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequestCustomer
     */
    'email': string;
    /**
     * 
     * @type {CustomerStatusNullable}
     * @memberof CreateQuoteRequestCustomer
     */
    'status'?: CustomerStatusNullable | null;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequestCustomer
     */
    'primary_market'?: string | null;
    /**
     * 
     * @type {AccountSourceNullable}
     * @memberof CreateQuoteRequestCustomer
     */
    'source'?: AccountSourceNullable | null;
    /**
     * 
     * @type {HearAboutUsNullable}
     * @memberof CreateQuoteRequestCustomer
     */
    'hear_about_us'?: HearAboutUsNullable | null;
    /**
     * 
     * @type {string}
     * @memberof CreateQuoteRequestCustomer
     */
    'owner_code'?: string | null;
}

