/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EstimationAccessFlags } from './estimation-access-flags';

/**
 * Access challenges for the property.
 * @export
 * @interface CreateQuoteInventoryRequestAccessFlags
 */
export interface CreateQuoteInventoryRequestAccessFlags {
    /**
     * 
     * @type {boolean}
     * @memberof CreateQuoteInventoryRequestAccessFlags
     */
    'elevator': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateQuoteInventoryRequestAccessFlags
     */
    'elevator_reserved': boolean;
    /**
     * 
     * @type {boolean}
     * @memberof CreateQuoteInventoryRequestAccessFlags
     */
    'long_walk_to_truck': boolean;
    /**
     * 
     * @type {number}
     * @memberof CreateQuoteInventoryRequestAccessFlags
     */
    'stair_flights': number;
}

