/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateQuoteRequestCustomer } from './create-quote-request-customer';
import { LocationRequest } from './location-request';
import { SetQuoteInventoryRequestNullable } from './set-quote-inventory-request-nullable';

/**
 * Create Quote Request
 * @export
 * @interface CreateQuoteRequest
 */
export interface CreateQuoteRequest {
    /**
     * 
     * @type {CreateQuoteRequestCustomer}
     * @memberof CreateQuoteRequest
     */
    'customer': CreateQuoteRequestCustomer;
    /**
     * Start date and time of the quote
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    'start_datetime': string;
    /**
     * Services to be quoted
     * @type {string}
     * @memberof CreateQuoteRequest
     */
    'service_code': string;
    /**
     * Mapping locations and their sequence
     * @type {{ [key: string]: LocationRequest; }}
     * @memberof CreateQuoteRequest
     */
    'locations': { [key: string]: LocationRequest; };
    /**
     * 
     * @type {SetQuoteInventoryRequestNullable}
     * @memberof CreateQuoteRequest
     */
    'inventory'?: SetQuoteInventoryRequestNullable | null;
}

