/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * TODO
 * @export
 * @interface EstimationResponse
 */
export interface EstimationResponse {
    /**
     * 
     * @type {number}
     * @memberof EstimationResponse
     */
    'crew_size': number;
    /**
     * 
     * @type {number}
     * @memberof EstimationResponse
     */
    'hours': number;
}

