/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"


/**
 * Inventory room slugs
 * @export
 * @enum {string}
 */
export type InventoryRoomSlug = 'attic' | 'bonus' | 'dining-room' | 'garage' | 'guest-bedroom' | 'gym' | 'kids-bedroom' | 'kitchen' | 'laundry' | 'living-room' | 'nursery' | 'office' | 'patio' | 'primary-bedroom' | 'storage-closet'

