/*
OpenAPI Petstore

This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

The version of the OpenAPI document: 1.0.0


NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { PaginateResponseEdges } from './paginate-response-edges';
import { PaginateResponsePageInfo } from './paginate-response-page-info';

/**
 * 
 * @export
 * @interface PaginateResponse
 */
export interface PaginateResponse {
    /**
     * 
     * @type {PaginateResponseEdges}
     * @memberof PaginateResponse
     */
    'edges'?: PaginateResponseEdges;
    /**
     * 
     * @type {PaginateResponsePageInfo}
     * @memberof PaginateResponse
     */
    'pageInfo'?: PaginateResponsePageInfo;
}

