/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InventoryRoomSlug } from './inventory-room-slug';

/**
 * Model for quote inventory rooms
 * @export
 * @interface QuoteInventoryRoom
 */
export interface QuoteInventoryRoom {
    /**
     * The name slug of the room.
     * @type {InventoryRoomSlug}
     * @memberof QuoteInventoryRoom
     */
    'slug': InventoryRoomSlug;
    /**
     * The count of the room.
     * @type {number}
     * @memberof QuoteInventoryRoom
     */
    'count': number;
}

