/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { InventoryItemSlug } from './inventory-item-slug';

/**
 * Model for quote inventory items
 * @export
 * @interface QuoteInventoryItem
 */
export interface QuoteInventoryItem {
    /**
     * The name slug of the item.
     * @type {InventoryItemSlug}
     * @memberof QuoteInventoryItem
     */
    'slug': InventoryItemSlug;
    /**
     * The count of the item.
     * @type {number}
     * @memberof QuoteInventoryItem
     */
    'count': number;
}

