/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { EstimationAccessFlags } from './estimation-access-flags';
import { MovingIntent } from './moving-intent';
import { QuoteInventoryItem } from './quote-inventory-item';
import { QuoteInventoryRoom } from './quote-inventory-room';

/**
 * Response model for quote inventory
 * @export
 * @interface QuoteInventoryResponse
 */
export interface QuoteInventoryResponse {
    /**
     * 
     * @type {string}
     * @memberof QuoteInventoryResponse
     */
    'id': string;
    /**
     * 
     * @type {string}
     * @memberof QuoteInventoryResponse
     */
    'quote_id': string;
    /**
     * 
     * @type {number}
     * @memberof QuoteInventoryResponse
     */
    'area': number;
    /**
     * 
     * @type {Array<QuoteInventoryRoom>}
     * @memberof QuoteInventoryResponse
     */
    'rooms': Array<QuoteInventoryRoom>;
    /**
     * 
     * @type {EstimationAccessFlags}
     * @memberof QuoteInventoryResponse
     */
    'access_flags': EstimationAccessFlags;
    /**
     * 
     * @type {MovingIntent}
     * @memberof QuoteInventoryResponse
     */
    'intent': MovingIntent;
    /**
     * 
     * @type {Array<QuoteInventoryItem>}
     * @memberof QuoteInventoryResponse
     */
    'additional_items'?: Array<QuoteInventoryItem> | null;
}

