/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { MovingIntentNullable } from './moving-intent-nullable';
import { QuoteInventoryItem } from './quote-inventory-item';
import { QuoteInventoryRoom } from './quote-inventory-room';
import { SetQuoteInventoryRequestAccessFlags } from './set-quote-inventory-request-access-flags';

/**
 * Inventory to be quoted
 * @export
 * @interface SetQuoteInventoryRequestNullable
 */
export interface SetQuoteInventoryRequestNullable {
    /**
     * The area of the property in square feet.
     * @type {number}
     * @memberof SetQuoteInventoryRequestNullable
     */
    'area': number;
    /**
     * The estimated amount of belongings to move.
     * @type {MovingIntentNullable}
     * @memberof SetQuoteInventoryRequestNullable
     */
    'intent'?: MovingIntentNullable | null;
    /**
     * List of rooms in the property.
     * @type {Array<QuoteInventoryRoom>}
     * @memberof SetQuoteInventoryRequestNullable
     */
    'rooms': Array<QuoteInventoryRoom>;
    /**
     * 
     * @type {SetQuoteInventoryRequestAccessFlags}
     * @memberof SetQuoteInventoryRequestNullable
     */
    'access_flags': SetQuoteInventoryRequestAccessFlags;
    /**
     * List of additional bulky items in the property.
     * @type {Array<QuoteInventoryItem>}
     * @memberof SetQuoteInventoryRequestNullable
     */
    'additional_items'?: Array<QuoteInventoryItem> | null;
}

