/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/
import type * as buffer from "buffer"

import { CreateQuoteInventoryRequestAccessFlags } from './create-quote-inventory-request-access-flags';
import { MovingIntentNullable } from './moving-intent-nullable';
import { QuoteInventoryItem } from './quote-inventory-item';
import { QuoteInventoryRoom } from './quote-inventory-room';

/**
 * Request body for updating room based inventory related to a quote
 * @export
 * @interface UpdateQuoteInventoryRequest
 */
export interface UpdateQuoteInventoryRequest {
    /**
     * The area of the property in square feet.
     * @type {number}
     * @memberof UpdateQuoteInventoryRequest
     */
    'area': number;
    /**
     * The estimated amount of belongings to move.
     * @type {MovingIntentNullable}
     * @memberof UpdateQuoteInventoryRequest
     */
    'intent'?: MovingIntentNullable | null;
    /**
     * List of rooms in the property.
     * @type {Array<QuoteInventoryRoom>}
     * @memberof UpdateQuoteInventoryRequest
     */
    'rooms': Array<QuoteInventoryRoom>;
    /**
     * 
     * @type {CreateQuoteInventoryRequestAccessFlags}
     * @memberof UpdateQuoteInventoryRequest
     */
    'access_flags': CreateQuoteInventoryRequestAccessFlags;
    /**
     * List of additional bulky items in the property.
     * @type {Array<QuoteInventoryItem>}
     * @memberof UpdateQuoteInventoryRequest
     */
    'additional_items'?: Array<QuoteInventoryItem> | null;
}

