/* tslint:disable */
/* eslint-disable */
/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { PostalCodesServiceabilityResponse } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * PostalCodeApi - axios parameter creator
 * @export
 */
export const PostalCodeApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Get Postal Codes Serviceability V5
         * @param {string} originPostalCode 
         * @param {string} [destinationPostalCode] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listServiceability: async (originPostalCode: string, destinationPostalCode?: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'originPostalCode' is not null or undefined
            assertParamExists('listServiceability', 'originPostalCode', originPostalCode)
            const localVarPath = `/postal-codes/serviceability`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)
            if (originPostalCode !== undefined) {
                localVarQueryParameter['origin_postal_code'] = originPostalCode;
            }

            if (destinationPostalCode !== undefined) {
                localVarQueryParameter['destination_postal_code'] = destinationPostalCode;
            }


    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * PostalCodeApi - functional programming interface
 * @export
 */
export const PostalCodeApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = PostalCodeApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Get Postal Codes Serviceability V5
         * @param {PostalCodeApiListServiceabilityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listServiceability(requestParameters: PostalCodeApiListServiceabilityRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<PostalCodesServiceabilityResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listServiceability(requestParameters.originPostalCode, requestParameters.destinationPostalCode, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * PostalCodeApi - factory interface
 * @export
 */
export const PostalCodeApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = PostalCodeApiFp(configuration)
    return {
        /**
         * 
         * @summary Get Postal Codes Serviceability V5
         * @param {PostalCodeApiListServiceabilityRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listServiceability(requestParameters: PostalCodeApiListServiceabilityRequest, options?: AxiosRequestConfig): AxiosPromise<PostalCodesServiceabilityResponse> {
            return localVarFp.listServiceability(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for listServiceability operation in PostalCodeApi.
 * @export
 * @interface PostalCodeApiListServiceabilityRequest
 */
export type PostalCodeApiListServiceabilityRequest = {
    
    /**
    * 
    * @type {string}
    * @memberof PostalCodeApiListServiceability
    */
    readonly originPostalCode: string
    
    /**
    * 
    * @type {string}
    * @memberof PostalCodeApiListServiceability
    */
    readonly destinationPostalCode?: string
    
}

/**
 * PostalCodeApiGenerated - object-oriented interface
 * @export
 * @class PostalCodeApiGenerated
 * @extends {BaseAPI}
 */
export class PostalCodeApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Get Postal Codes Serviceability V5
     * @param {PostalCodeApiListServiceabilityRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof PostalCodeApiGenerated
     */
    public listServiceability(requestParameters: PostalCodeApiListServiceabilityRequest, options?: AxiosRequestConfig) {
        return PostalCodeApiFp(this.configuration).listServiceability(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
