/* tslint:disable */
/* eslint-disable */
/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { MovingIntentNullable } from '../models';
// @ts-ignore
import { QuoteInventoryItem } from '../models';
// @ts-ignore
import { QuoteInventoryResponse } from '../models';
// @ts-ignore
import { QuoteInventoryRoom } from '../models';
// @ts-ignore
import { SetQuoteInventoryRequest } from '../models';
// @ts-ignore
import { SetQuoteInventoryRequestAccessFlags } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * QuoteInventoryApi - axios parameter creator
 * @export
 */
export const QuoteInventoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {string} quoteId UUID of the inventory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInventory: async (quoteId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('deleteInventory', 'quoteId', quoteId)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {string} quoteId UUID of the source quote
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInventory: async (quoteId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('listInventory', 'quoteId', quoteId)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {string} quoteId UUID of the inventory
         * @param {SetQuoteInventoryRequest} setQuoteInventoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInventory: async (quoteId: string, setQuoteInventoryRequest: SetQuoteInventoryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('updateInventory', 'quoteId', quoteId)
            // verify required parameter 'setQuoteInventoryRequest' is not null or undefined
            assertParamExists('updateInventory', 'setQuoteInventoryRequest', setQuoteInventoryRequest)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: setQuoteInventoryRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });
            localVarRequestOptions.data = serializeDataIfNeeded(setQuoteInventoryRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuoteInventoryApi - functional programming interface
 * @export
 */
export const QuoteInventoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuoteInventoryApiAxiosParamCreator(configuration)
    return {
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {QuoteInventoryApiDeleteInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteInventory(requestParameters: QuoteInventoryApiDeleteInventoryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteInventory(requestParameters.quoteId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {QuoteInventoryApiListInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async listInventory(requestParameters: QuoteInventoryApiListInventoryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteInventoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.listInventory(requestParameters.quoteId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {QuoteInventoryApiUpdateInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateInventory(requestParameters: QuoteInventoryApiUpdateInventoryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteInventoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateInventory(requestParameters.quoteId, requestParameters, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * QuoteInventoryApi - factory interface
 * @export
 */
export const QuoteInventoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuoteInventoryApiFp(configuration)
    return {
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {QuoteInventoryApiDeleteInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInventory(requestParameters: QuoteInventoryApiDeleteInventoryRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteInventory(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {QuoteInventoryApiListInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        listInventory(requestParameters: QuoteInventoryApiListInventoryRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteInventoryResponse> {
            return localVarFp.listInventory(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {QuoteInventoryApiUpdateInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInventory(requestParameters: QuoteInventoryApiUpdateInventoryRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteInventoryResponse> {
            return localVarFp.updateInventory(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for deleteInventory operation in QuoteInventoryApi.
 * @export
 * @interface QuoteInventoryApiDeleteInventoryRequest
 */
export type QuoteInventoryApiDeleteInventoryRequest = {
    
    /**
    * UUID of the inventory
    * @type {string}
    * @memberof QuoteInventoryApiDeleteInventory
    */
    readonly quoteId: string
    
}

/**
 * Request parameters for listInventory operation in QuoteInventoryApi.
 * @export
 * @interface QuoteInventoryApiListInventoryRequest
 */
export type QuoteInventoryApiListInventoryRequest = {
    
    /**
    * UUID of the source quote
    * @type {string}
    * @memberof QuoteInventoryApiListInventory
    */
    readonly quoteId: string
    
}

/**
 * Request parameters for updateInventory operation in QuoteInventoryApi.
 * @export
 * @interface QuoteInventoryApiUpdateInventoryRequest
 */
export type QuoteInventoryApiUpdateInventoryRequest = {
    
    /**
    * UUID of the inventory
    * @type {string}
    * @memberof QuoteInventoryApiUpdateInventory
    */
    readonly quoteId: string
    
} & SetQuoteInventoryRequest

/**
 * QuoteInventoryApiGenerated - object-oriented interface
 * @export
 * @class QuoteInventoryApiGenerated
 * @extends {BaseAPI}
 */
export class QuoteInventoryApiGenerated extends BaseAPI {
    /**
     * 
     * @summary Delete Quote Inventory
     * @param {QuoteInventoryApiDeleteInventoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteInventoryApiGenerated
     */
    public deleteInventory(requestParameters: QuoteInventoryApiDeleteInventoryRequest, options?: AxiosRequestConfig) {
        return QuoteInventoryApiFp(this.configuration).deleteInventory(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Quote Inventory
     * @param {QuoteInventoryApiListInventoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteInventoryApiGenerated
     */
    public listInventory(requestParameters: QuoteInventoryApiListInventoryRequest, options?: AxiosRequestConfig) {
        return QuoteInventoryApiFp(this.configuration).listInventory(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Quote Inventory
     * @param {QuoteInventoryApiUpdateInventoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteInventoryApiGenerated
     */
    public updateInventory(requestParameters: QuoteInventoryApiUpdateInventoryRequest, options?: AxiosRequestConfig) {
        return QuoteInventoryApiFp(this.configuration).updateInventory(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
