/* tslint:disable */
/* eslint-disable */
/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
import { setOAuthToObject } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateQuoteRequest } from '../models';
// @ts-ignore
import { CreateQuoteRequestCustomer } from '../models';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { LocationRequest } from '../models';
// @ts-ignore
import { MovingIntentNullable } from '../models';
// @ts-ignore
import { QuoteInventoryItem } from '../models';
// @ts-ignore
import { QuoteInventoryResponse } from '../models';
// @ts-ignore
import { QuoteInventoryRoom } from '../models';
// @ts-ignore
import { QuoteResponse } from '../models';
// @ts-ignore
import { SetQuoteInventoryRequest } from '../models';
// @ts-ignore
import { SetQuoteInventoryRequestAccessFlags } from '../models';
// @ts-ignore
import { SetQuoteInventoryRequestNullable } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * QuoteApi - axios parameter creator
 * @export
 */
export const QuoteApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a quote  Creates a quote for a given customer using the provided locations and service code. The LOCALFULLSERVICE service code will generate a service group with LOADINGUNLOADING and TRANSIT services. All other service codes generate service groups with a single service.
         * @summary Create Quote
         * @param {CreateQuoteRequest} createQuoteRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (createQuoteRequest: CreateQuoteRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'createQuoteRequest' is not null or undefined
            assertParamExists('create', 'createQuoteRequest', createQuoteRequest)
            const localVarPath = `/quotes`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2ImplicitBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2ImplicitBearer", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createQuoteRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createQuoteRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {string} quoteId UUID of the inventory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInventory: async (quoteId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('deleteInventory', 'quoteId', quoteId)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2ImplicitBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2ImplicitBearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * Fetch a quote by ID
         * @summary Get Quote
         * @param {string} quoteId UUID of the quote
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (quoteId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('get', 'quoteId', quoteId)
            const localVarPath = `/quotes/{quote_id}`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2ImplicitBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2ImplicitBearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {string} quoteId UUID of the source quote
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInventory: async (quoteId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('getInventory', 'quoteId', quoteId)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2ImplicitBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2ImplicitBearer", [], configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {string} quoteId UUID of the inventory
         * @param {SetQuoteInventoryRequest} setQuoteInventoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInventory: async (quoteId: string, setQuoteInventoryRequest: SetQuoteInventoryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('updateInventory', 'quoteId', quoteId)
            // verify required parameter 'setQuoteInventoryRequest' is not null or undefined
            assertParamExists('updateInventory', 'setQuoteInventoryRequest', setQuoteInventoryRequest)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication OAuth2ImplicitBearer required
            // oauth required
            await setOAuthToObject(localVarHeaderParameter, "OAuth2ImplicitBearer", [], configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: setQuoteInventoryRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });
            localVarRequestOptions.data = serializeDataIfNeeded(setQuoteInventoryRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuoteApi - functional programming interface
 * @export
 */
export const QuoteApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuoteApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a quote  Creates a quote for a given customer using the provided locations and service code. The LOCALFULLSERVICE service code will generate a service group with LOADINGUNLOADING and TRANSIT services. All other service codes generate service groups with a single service.
         * @summary Create Quote
         * @param {QuoteApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(requestParameters: QuoteApiCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(requestParameters, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {QuoteApiDeleteInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async deleteInventory(requestParameters: QuoteApiDeleteInventoryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.deleteInventory(requestParameters.quoteId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * Fetch a quote by ID
         * @summary Get Quote
         * @param {QuoteApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(requestParameters: QuoteApiGetRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(requestParameters.quoteId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {QuoteApiGetInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async getInventory(requestParameters: QuoteApiGetInventoryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteInventoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.getInventory(requestParameters.quoteId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {QuoteApiUpdateInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async updateInventory(requestParameters: QuoteApiUpdateInventoryRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteInventoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.updateInventory(requestParameters.quoteId, requestParameters, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * QuoteApi - factory interface
 * @export
 */
export const QuoteApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuoteApiFp(configuration)
    return {
        /**
         * Creates a quote  Creates a quote for a given customer using the provided locations and service code. The LOCALFULLSERVICE service code will generate a service group with LOADINGUNLOADING and TRANSIT services. All other service codes generate service groups with a single service.
         * @summary Create Quote
         * @param {QuoteApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(requestParameters: QuoteApiCreateRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteResponse> {
            return localVarFp.create(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {QuoteApiDeleteInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        deleteInventory(requestParameters: QuoteApiDeleteInventoryRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.deleteInventory(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * Fetch a quote by ID
         * @summary Get Quote
         * @param {QuoteApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(requestParameters: QuoteApiGetRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteResponse> {
            return localVarFp.get(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {QuoteApiGetInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        getInventory(requestParameters: QuoteApiGetInventoryRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteInventoryResponse> {
            return localVarFp.getInventory(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {QuoteApiUpdateInventoryRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        updateInventory(requestParameters: QuoteApiUpdateInventoryRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteInventoryResponse> {
            return localVarFp.updateInventory(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for create operation in QuoteApi.
 * @export
 * @interface QuoteApiCreateRequest
 */
export type QuoteApiCreateRequest = {
    
} & CreateQuoteRequest

/**
 * Request parameters for deleteInventory operation in QuoteApi.
 * @export
 * @interface QuoteApiDeleteInventoryRequest
 */
export type QuoteApiDeleteInventoryRequest = {
    
    /**
    * UUID of the inventory
    * @type {string}
    * @memberof QuoteApiDeleteInventory
    */
    readonly quoteId: string
    
}

/**
 * Request parameters for get operation in QuoteApi.
 * @export
 * @interface QuoteApiGetRequest
 */
export type QuoteApiGetRequest = {
    
    /**
    * UUID of the quote
    * @type {string}
    * @memberof QuoteApiGet
    */
    readonly quoteId: string
    
}

/**
 * Request parameters for getInventory operation in QuoteApi.
 * @export
 * @interface QuoteApiGetInventoryRequest
 */
export type QuoteApiGetInventoryRequest = {
    
    /**
    * UUID of the source quote
    * @type {string}
    * @memberof QuoteApiGetInventory
    */
    readonly quoteId: string
    
}

/**
 * Request parameters for updateInventory operation in QuoteApi.
 * @export
 * @interface QuoteApiUpdateInventoryRequest
 */
export type QuoteApiUpdateInventoryRequest = {
    
    /**
    * UUID of the inventory
    * @type {string}
    * @memberof QuoteApiUpdateInventory
    */
    readonly quoteId: string
    
} & SetQuoteInventoryRequest

/**
 * QuoteApiGenerated - object-oriented interface
 * @export
 * @class QuoteApiGenerated
 * @extends {BaseAPI}
 */
export class QuoteApiGenerated extends BaseAPI {
    /**
     * Creates a quote  Creates a quote for a given customer using the provided locations and service code. The LOCALFULLSERVICE service code will generate a service group with LOADINGUNLOADING and TRANSIT services. All other service codes generate service groups with a single service.
     * @summary Create Quote
     * @param {QuoteApiCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteApiGenerated
     */
    public create(requestParameters: QuoteApiCreateRequest, options?: AxiosRequestConfig) {
        return QuoteApiFp(this.configuration).create(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Quote Inventory
     * @param {QuoteApiDeleteInventoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteApiGenerated
     */
    public deleteInventory(requestParameters: QuoteApiDeleteInventoryRequest, options?: AxiosRequestConfig) {
        return QuoteApiFp(this.configuration).deleteInventory(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * Fetch a quote by ID
     * @summary Get Quote
     * @param {QuoteApiGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteApiGenerated
     */
    public get(requestParameters: QuoteApiGetRequest, options?: AxiosRequestConfig) {
        return QuoteApiFp(this.configuration).get(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Quote Inventory
     * @param {QuoteApiGetInventoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteApiGenerated
     */
    public getInventory(requestParameters: QuoteApiGetInventoryRequest, options?: AxiosRequestConfig) {
        return QuoteApiFp(this.configuration).getInventory(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Quote Inventory
     * @param {QuoteApiUpdateInventoryRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteApiGenerated
     */
    public updateInventory(requestParameters: QuoteApiUpdateInventoryRequest, options?: AxiosRequestConfig) {
        return QuoteApiFp(this.configuration).updateInventory(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
