/* tslint:disable */
/* eslint-disable */
/*
partner-api

Bellhop's Partner API

The version of the OpenAPI document: 5
Contact: engineering@bellhop.com

NOTE: This file is auto generated by Konfig (https://konfigthis.com).
*/

import globalAxios, { AxiosPromise, AxiosInstance, AxiosRequestConfig } from 'axios';
import { Configuration } from '../configuration';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction, isBrowser } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, RequestArgs, BaseAPI, RequiredError } from '../base';
// @ts-ignore
import { CreateQuoteInventoryRequest } from '../models';
// @ts-ignore
import { CreateQuoteInventoryRequestAccessFlags } from '../models';
// @ts-ignore
import { HTTPValidationError } from '../models';
// @ts-ignore
import { MovingIntentNullable } from '../models';
// @ts-ignore
import { QuoteInventoryItem } from '../models';
// @ts-ignore
import { QuoteInventoryResponse } from '../models';
// @ts-ignore
import { QuoteInventoryRoom } from '../models';
// @ts-ignore
import { UpdateQuoteInventoryRequest } from '../models';
import { paginate } from "../pagination/paginate";
import type * as buffer from "buffer"
import { requestBeforeHook } from '../requestBeforeHook';
/**
 * QuoteInventoryApi - axios parameter creator
 * @export
 */
export const QuoteInventoryApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * Creates a quote inventory object on a quote
         * @summary Create Quote Inventory
         * @param {string} quoteId UUID of the source quote
         * @param {CreateQuoteInventoryRequest} createQuoteInventoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create: async (quoteId: string, createQuoteInventoryRequest: CreateQuoteInventoryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('create', 'quoteId', quoteId)
            // verify required parameter 'createQuoteInventoryRequest' is not null or undefined
            assertParamExists('create', 'createQuoteInventoryRequest', createQuoteInventoryRequest)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: createQuoteInventoryRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });
            localVarRequestOptions.data = serializeDataIfNeeded(createQuoteInventoryRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {string} inventoryId UUID of the inventory
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete: async (inventoryId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inventoryId' is not null or undefined
            assertParamExists('delete', 'inventoryId', inventoryId)
            const localVarPath = `/quotes/{inventory_id}/inventory`
                .replace(`{${"inventory_id"}}`, encodeURIComponent(String(inventoryId !== undefined ? inventoryId : `-inventory_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {string} quoteId UUID of the source quote
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get: async (quoteId: string, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'quoteId' is not null or undefined
            assertParamExists('get', 'quoteId', quoteId)
            const localVarPath = `/quotes/{quote_id}/inventory`
                .replace(`{${"quote_id"}}`, encodeURIComponent(String(quoteId !== undefined ? quoteId : `-quote_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {string} inventoryId UUID of the inventory
         * @param {UpdateQuoteInventoryRequest} updateQuoteInventoryRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update: async (inventoryId: string, updateQuoteInventoryRequest: UpdateQuoteInventoryRequest, options: AxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'inventoryId' is not null or undefined
            assertParamExists('update', 'inventoryId', inventoryId)
            // verify required parameter 'updateQuoteInventoryRequest' is not null or undefined
            assertParamExists('update', 'updateQuoteInventoryRequest', updateQuoteInventoryRequest)
            const localVarPath = `/quotes/{inventory_id}/inventory`
                .replace(`{${"inventory_id"}}`, encodeURIComponent(String(inventoryId !== undefined ? inventoryId : `-inventory_id-`)));
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions: AxiosRequestConfig = { method: 'PUT', ...baseOptions, ...options};
            const localVarHeaderParameter = configuration && !isBrowser() ? { "User-Agent": configuration.userAgent } : {} as any;
            const localVarQueryParameter = {} as any;

            // authentication Auth0HTTPBearer required
            // http bearer authentication required
            await setBearerAuthToObject(localVarHeaderParameter, configuration)

    
            localVarHeaderParameter['Content-Type'] = 'application/json';


            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            requestBeforeHook({
                requestBody: updateQuoteInventoryRequest,
                queryParameters: localVarQueryParameter,
                requestConfig: localVarRequestOptions,
                path: localVarPath,
                configuration
            });
            localVarRequestOptions.data = serializeDataIfNeeded(updateQuoteInventoryRequest, localVarRequestOptions, configuration)

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * QuoteInventoryApi - functional programming interface
 * @export
 */
export const QuoteInventoryApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = QuoteInventoryApiAxiosParamCreator(configuration)
    return {
        /**
         * Creates a quote inventory object on a quote
         * @summary Create Quote Inventory
         * @param {QuoteInventoryApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async create(requestParameters: QuoteInventoryApiCreateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteInventoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.create(requestParameters.quoteId, requestParameters, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {QuoteInventoryApiDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async delete(requestParameters: QuoteInventoryApiDeleteRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<void>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.delete(requestParameters.inventoryId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {QuoteInventoryApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async get(requestParameters: QuoteInventoryApiGetRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteInventoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.get(requestParameters.quoteId, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {QuoteInventoryApiUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async update(requestParameters: QuoteInventoryApiUpdateRequest, options?: AxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<QuoteInventoryResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.update(requestParameters.inventoryId, requestParameters, options);
            return createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration);
        },
    }
};

/**
 * QuoteInventoryApi - factory interface
 * @export
 */
export const QuoteInventoryApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = QuoteInventoryApiFp(configuration)
    return {
        /**
         * Creates a quote inventory object on a quote
         * @summary Create Quote Inventory
         * @param {QuoteInventoryApiCreateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        create(requestParameters: QuoteInventoryApiCreateRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteInventoryResponse> {
            return localVarFp.create(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Delete Quote Inventory
         * @param {QuoteInventoryApiDeleteRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        delete(requestParameters: QuoteInventoryApiDeleteRequest, options?: AxiosRequestConfig): AxiosPromise<void> {
            return localVarFp.delete(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Get Quote Inventory
         * @param {QuoteInventoryApiGetRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        get(requestParameters: QuoteInventoryApiGetRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteInventoryResponse> {
            return localVarFp.get(requestParameters, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @summary Update Quote Inventory
         * @param {QuoteInventoryApiUpdateRequest} requestParameters Request parameters.
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        update(requestParameters: QuoteInventoryApiUpdateRequest, options?: AxiosRequestConfig): AxiosPromise<QuoteInventoryResponse> {
            return localVarFp.update(requestParameters, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * Request parameters for create operation in QuoteInventoryApi.
 * @export
 * @interface QuoteInventoryApiCreateRequest
 */
export type QuoteInventoryApiCreateRequest = {
    
    /**
    * UUID of the source quote
    * @type {string}
    * @memberof QuoteInventoryApiCreate
    */
    readonly quoteId: string
    
} & CreateQuoteInventoryRequest

/**
 * Request parameters for delete operation in QuoteInventoryApi.
 * @export
 * @interface QuoteInventoryApiDeleteRequest
 */
export type QuoteInventoryApiDeleteRequest = {
    
    /**
    * UUID of the inventory
    * @type {string}
    * @memberof QuoteInventoryApiDelete
    */
    readonly inventoryId: string
    
}

/**
 * Request parameters for get operation in QuoteInventoryApi.
 * @export
 * @interface QuoteInventoryApiGetRequest
 */
export type QuoteInventoryApiGetRequest = {
    
    /**
    * UUID of the source quote
    * @type {string}
    * @memberof QuoteInventoryApiGet
    */
    readonly quoteId: string
    
}

/**
 * Request parameters for update operation in QuoteInventoryApi.
 * @export
 * @interface QuoteInventoryApiUpdateRequest
 */
export type QuoteInventoryApiUpdateRequest = {
    
    /**
    * UUID of the inventory
    * @type {string}
    * @memberof QuoteInventoryApiUpdate
    */
    readonly inventoryId: string
    
} & UpdateQuoteInventoryRequest

/**
 * QuoteInventoryApiGenerated - object-oriented interface
 * @export
 * @class QuoteInventoryApiGenerated
 * @extends {BaseAPI}
 */
export class QuoteInventoryApiGenerated extends BaseAPI {
    /**
     * Creates a quote inventory object on a quote
     * @summary Create Quote Inventory
     * @param {QuoteInventoryApiCreateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteInventoryApiGenerated
     */
    public create(requestParameters: QuoteInventoryApiCreateRequest, options?: AxiosRequestConfig) {
        return QuoteInventoryApiFp(this.configuration).create(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Delete Quote Inventory
     * @param {QuoteInventoryApiDeleteRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteInventoryApiGenerated
     */
    public delete(requestParameters: QuoteInventoryApiDeleteRequest, options?: AxiosRequestConfig) {
        return QuoteInventoryApiFp(this.configuration).delete(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Get Quote Inventory
     * @param {QuoteInventoryApiGetRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteInventoryApiGenerated
     */
    public get(requestParameters: QuoteInventoryApiGetRequest, options?: AxiosRequestConfig) {
        return QuoteInventoryApiFp(this.configuration).get(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @summary Update Quote Inventory
     * @param {QuoteInventoryApiUpdateRequest} requestParameters Request parameters.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof QuoteInventoryApiGenerated
     */
    public update(requestParameters: QuoteInventoryApiUpdateRequest, options?: AxiosRequestConfig) {
        return QuoteInventoryApiFp(this.configuration).update(requestParameters, options).then((request) => request(this.axios, this.basePath));
    }
}
