# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import unittest
from unittest.mock import patch

import urllib3

import bellhop
from bellhop.paths.store_order_order_id import delete
from bellhop import configuration, schemas, api_client

from .. import ApiTestMixin


class TestStoreOrderOrderId(ApiTestMixin, unittest.TestCase):
    """
    StoreOrderOrderId unit test stubs
        Delete purchase order by ID
    """

    def setUp(self):
        pass

    def tearDown(self):
        pass

    response_status = 200
    response_body = ''


if __name__ == '__main__':
    unittest.main()
