# coding: utf-8
"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

import typing
import inspect
from datetime import date, datetime
from bellhop.client_custom import ClientCustom
from bellhop.configuration import Configuration
from bellhop.api_client import ApiClient
from bellhop.type_util import copy_signature
from bellhop.apis.tags.miscellaneous_api import MiscellaneousApi
from bellhop.apis.tags.pet_api import PetApi
from bellhop.apis.tags.store_api import StoreApi
from bellhop.apis.tags.user_api import UserApi



class Bellhop(ClientCustom):

    def __init__(self, configuration: typing.Union[Configuration, None] = None, **kwargs):
        super().__init__(configuration, **kwargs)
        if (len(kwargs) > 0):
            configuration = Configuration(**kwargs)
        if (configuration is None):
            raise Exception("configuration is required")
        api_client = ApiClient(configuration)
        self.miscellaneous: MiscellaneousApi = MiscellaneousApi(api_client)
        self.pet: PetApi = PetApi(api_client)
        self.store: StoreApi = StoreApi(api_client)
        self.user: UserApi = UserApi(api_client)
