# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from bellhop.paths.pagination.get import Paginate
from bellhop.apis.tags.miscellaneous_api_raw import MiscellaneousApiRaw


class MiscellaneousApi(
    Paginate,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    raw: MiscellaneousApiRaw

    def __init__(self, api_client=None):
        super().__init__(api_client)
        self.raw = MiscellaneousApiRaw(api_client)
