# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from bellhop.paths.pet.post import AddRaw
from bellhop.paths.pet_pet_id.delete import DeleteRaw
from bellhop.paths.pet_find_by_status.get import FindByStatusRaw
from bellhop.paths.pet_find_by_tags.get import FindByTagsRaw
from bellhop.paths.pet_pet_id.get import GetByIdRaw
from bellhop.paths.pet.put import UpdateRaw
from bellhop.paths.pet_pet_id.post import UpdateWithFormRaw
from bellhop.paths.pet_pet_id_upload_image.post import UploadImageRaw


class PetApiRaw(
    AddRaw,
    DeleteRaw,
    FindByStatusRaw,
    FindByTagsRaw,
    GetByIdRaw,
    UpdateRaw,
    UpdateWithFormRaw,
    UploadImageRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
