# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from bellhop.paths.user.post import CreateRaw
from bellhop.paths.user_create_with_array.post import CreateWithArrayRaw
from bellhop.paths.user_create_with_list.post import CreateWithListRaw
from bellhop.paths.user_username.delete import DeleteRaw
from bellhop.paths.user_username.get import GetByNameRaw
from bellhop.paths.user_login.get import LoginRaw
from bellhop.paths.user_logout.get import LogoutRaw
from bellhop.paths.user_username.put import UpdateRaw


class UserApiRaw(
    CreateRaw,
    CreateWithArrayRaw,
    CreateWithListRaw,
    DeleteRaw,
    GetByNameRaw,
    LoginRaw,
    LogoutRaw,
    UpdateRaw,
):
    """NOTE:
    This class is auto generated by Konfig (https://konfigthis.com)
    """
    pass
