# coding: utf-8

"""
    OpenAPI Petstore

    This is a sample server Petstore server. For this sample, you can use the api key `special-key` to test the authorization filters.

    The version of the OpenAPI document: 1.0.0
    Generated by: https://konfigthis.com
"""

from datetime import datetime, date
import typing
from enum import Enum
from typing_extensions import TypedDict, Literal, TYPE_CHECKING
from pydantic import BaseModel, Field, RootModel

from bellhop.pydantic.category import Category
from bellhop.pydantic.pet_photo_urls import PetPhotoUrls
from bellhop.pydantic.tag import Tag

class Pet(BaseModel):
    name: str = Field(alias='name')

    photo_urls: PetPhotoUrls = Field(alias='photoUrls')

    tags: typing.Optional[typing.List[Tag]] = Field(None, alias='tags')

    id: typing.Optional[int] = Field(None, alias='id')

    category: typing.Optional[Category] = Field(None, alias='category')

    # pet status in the store
    status: typing.Optional[str] = Field(None, alias='status')
